name: 'pop-compose'

services:

  iam:
    container_name: popiam
    image: quay.io/keycloak/keycloak:24.0.4
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://popdb:5432/keycloak
      KC_DB_USERNAME: localhost
      KC_DB_PASSWORD: root
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: 
      - start-dev
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    container_name: popdb
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: localhost
      POSTGRES_PASSWORD: root
    volumes:
      - popdb:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  popdb: